# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 15:33
from __future__ import unicode_literals

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contacts',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=contacts.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
