# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenue',
            old_name='cost',
            new_name='field_visit_revenue',
        ),
        migrations.RenameField(
            model_name='revenue',
            old_name='service',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='revenue',
            old_name='rate',
            new_name='print_map_rate',
        ),
        migrations.AddField(
            model_name='revenue',
            name='print_map_revenue',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenue',
            name='total_print_map_num',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenue',
            name='total_trace_map_num',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenue',
            name='trace_map_rate',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenue',
            name='trace_map_revenue',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
