# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_auto_20160429_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='total_revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='month',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='print_map_rate',
            field=models.CharField(default=100, max_length=120),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='trace_map_rate',
            field=models.CharField(default=100, max_length=120),
        ),
    ]
