# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20160423_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_amount',
            field=models.CharField(default=0, max_length=120, verbose_name='Budget Number'),
            preserve_default=False,
        ),
    ]
