# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_budget_budget_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_amount',
            field=models.CharField(max_length=120, verbose_name='Budget Amount'),
        ),
    ]
