# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_demarcation_revenue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddemarcationrevenue',
            name='distance',
            field=models.IntegerField(max_length=120, verbose_name='Distance(Miles)'),
        ),
        migrations.AlterField(
            model_name='fielddemarcationrevenue',
            name='sn',
            field=models.CharField(default='1', max_length=120, verbose_name='SN'),
        ),
    ]
