# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_demarcation_revenue', '0002_auto_20160614_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fielddemarcationrevenue',
            name='sn',
        ),
        migrations.AlterField(
            model_name='fielddemarcationrevenue',
            name='distance',
            field=models.CharField(max_length=120, verbose_name='Distance(Miles)'),
        ),
        migrations.AlterField(
            model_name='fielddemarcationrevenue',
            name='remarks',
            field=models.CharField(default='N/A', max_length=120, verbose_name='Remarks'),
        ),
    ]
