# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacks',
            old_name='publish',
            new_name='date',
        ),
    ]
